name: Publish the container build
inputs:
  aws-org-id:
    description: "The AWS organization"
    required: true
    type: string

  devel-keep-days:
    description: "The number of days to keep devel- builds for"
    required: false
    type: number
    default: 30

  snapshot-keep-days:
    description: "The number of days to keep SNAPSHOT builds for"
    required: false
    type: number
    default: 30

runs:
  using: composite
  steps:
    - name: Create the ECR Repositories (if applicable)
      run: |
        "${GITHUB_ACTION_PATH}/create-repository.sh"

    - name: Create Access Permissions
      env:
        AWS_ORG_ID: ${{ inputs.aws-org-id }}
      run: |
        "${GITHUB_ACTION_PATH}/permissions.sh"

    - name: Create Lifecycle Policy
      env:
        SNAPSHOT_KEEP_DAYS: ${{ inputs.snapshot-keep-days }}
        DEVEL_KEEP_DAYS: ${{ inputs.devel-keep-days }}
      run: |
        "${GITHUB_ACTION_PATH}/lifecycle-policy.sh"

    - name: Publish the Docker Image (and all its tags)
      run: |
        "${GITHUB_ACTION_PATH}/publish.sh"
