name: Build Armedia Docker Containers
on:
  workflow_call:
    inputs:
      revision:
        description: "The revision number to use for construction (computed from the Dockerfile if not provided)"
        required: false
        type: string

      portal:
        description: "The FOIA Portal version to use for construction (computed from the Dockerfile if not provided)"
        required: false
        type: string

      reports-bucket:
        description: "The bucket into which to upload the STIG Compliance and Vulnerability reports (defaults to 'arkcase-container-scan-results')"
        required: false
        type: string
        default: "arkcase-container-scan-results"

      maximize-build-space:
        description: "Whether or not to maximize the build space by removing unnecessary tools & libraries"
        required: false
        type: boolean
        default: false

      scanner-image:
        description: "The container image to use for compliance and vulnerability scanning"
        required: false
        type: string

      compliance-scan:
        description: "Whether or not to scan for STIG compliance on the build"
        required: false
        type: boolean
        # Start of false, for testing...
        default: true

      compliance-required:
        description: "Whether or not to require full STIG compliance to approve the build (default false)"
        required: false
        type: boolean
        default: false

      vulnerabilities-scan:
        description: "Whether or not to scan for vulnerabilities on the build"
        required: false
        type: boolean
        default: true

      vulnerabilities-required:
        description: "Whether or not to require no CRIT or HIGH vulnerabilities to approve the build (default false)"
        required: false
        type: boolean
        default: false

      devel-keep-days:
        description: "How many days to keep 'devel-' tags"
        required: false
        type: number
        default: 30

      snapshot-keep-days:
        description: "How many days to keep 'SNAPSHOT' tags"
        required: false
        type: number
        default: 30

    secrets:
      #
      # For AWS/S3 access
      #
      ECR_AWS_REGION:
        required: true
      ECR_AWS_ORG_ID:
        required: true
      ECR_AWS_ACCESS_KEY:
        required: true
      ECR_AWS_SECRET_ACCESS_KEY:
        required: true

      # Vestigial, needs to be removed
      ECR_AWS_ACCOUNT_ID:
        required: false

      #
      # For Alfresco base container image access
      #
      ALF_QUAY_IO_USERNAME:
        required: false
      ALF_QUAY_IO_PASSWORD:
        required: false

      #
      # For Chainguard access
      #
      CHAINGUARD_USERNAME:
        required: false
      CHAINGUARD_PASSWORD:
        required: false

      #
      # To download private web-hosted artifacts
      #
      CURL_ENCRYPTION_KEY:
        required: false
      CURL_AUTH_FILE:
        required: false
      CURL_USERNAME:
        required: false
      CURL_PASSWORD:
        required: false

      #
      # To download private Maven artifacts
      #
      MVN_GET_ENCRYPTION_KEY:
        required: false
      MVN_GET_USERNAME:
        required: false
      MVN_GET_PASSWORD:
        required: false

env:
  GH_TOKEN: ${{ github.token }}

jobs:

  #
  # First, compute the build matrix for this run. This means that if the container
  # requires several versions/variants to be built, then these must be enumerated
  #
  Compute-Revisions:
    runs-on: ubuntu-24.04

    steps:
      # This is inefficient, but necessary b/c we may not share
      # the worker with the actual build's actions, below
      - name: Checkout source code
        uses: actions/checkout@v6

      - id: compute-matrix
        name: Compute alternate revisions and variants to be built
        uses: arkcase/github-action-templates/compute-matrix@develop
        with:
          revision: ${{ inputs.revision }}
          portal: ${{ inputs.portal }}

    outputs:
      revisions: ${{ steps.compute-matrix.outputs.revisions }}
      variants: ${{ steps.compute-matrix.outputs.variants }}

  #
  # Once we've figured out which builds we need to run, we run them!
  #
  Build-and-Publish:
    needs: [ "Compute-Revisions" ]
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        revision: ${{ fromJSON(needs.Compute-Revisions.outputs.revisions) }}
        variant: ${{ fromJSON(needs.Compute-Revisions.outputs.variants) }}

    steps:
      # This is inefficient, but necessary b/c we may not share
      # the worker with the matrix computation actions, above
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Build the Container Image
        uses: arkcase/github-action-templates/build@develop
        with:
          # General build parameters
          local-registry: ${{ env.LOCAL_REGISTRY }}
          matrix-revision: ${{ matrix.revision }}
          matrix-variant: ${{ matrix.variant }}
          revision: ${{ inputs.revision }}
          portal: ${{ inputs.portal }}

          # In case we need more disk space
          maximize-build-space: ${{ inputs.maximize-build-space }}

          # AWS Access Secrets
          aws-org-id: ${{ secrets.ECR_AWS_ORG_ID }}
          aws-region: ${{ secrets.ECR_AWS_REGION }}
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}

          # Alfresco's Quay.IO Credentials
          alf-quay-io-username: ${{ secrets.ALF_QUAY_IO_USERNAME }}
          alf-quay-io-password: ${{ secrets.ALF_QUAY_IO_PASSWORD }}

          # Chainguard Credentials
          chainguard-username: ${{ secrets.CHAINGUARD_USERNAME }}
          chainguard-password: ${{ secrets.CHAINGUARD_PASSWORD }}

          # For general cURL-get authentication
          curl-encryption-key: ${{ secrets.CURL_ENCRYPTION_KEY }}
          curl-username: ${{ secrets.CURL_USERNAME }}
          curl-password: ${{ secrets.CURL_PASSWORD }}

          # For general Maven authentication
          mvn-get-encryption-key: ${{ secrets.MVN_GET_ENCRYPTION_KEY }}
          mvn-get-username: ${{ secrets.MVN_GET_USERNAME }}
          mvn-get-password: ${{ secrets.MVN_GET_PASSWORD }}

          # Parameters for security scanning
          scanner-image: ${{ inputs.scanner-image }}
          reports-bucket: ${{ inputs.reports-bucket }}
          compliance-scan: ${{ inputs.compliance-scan }}
          compliance-required: ${{ inputs.compliance-required }}
          vulnerabilities-scan: ${{ inputs.vulnerabilities-scan }}
          vulnerabilities-required: ${{ inputs.vulnerabilities-required }}

          # For ECR repository policies
          devel-keep-days: ${{ inputs.devel-keep-days }}
          snapshot-keep-days: ${{ inputs.snapshot-keep-days }}
